#!/bin/bash
set -e

# Note: we don't just use "apache2ctl" here because it itself is just a shell-script wrapper around apache2 which provides extra functionality like "apache2ctl start" for launching apache2 in the background.
# (also, when run as "apache2ctl <apache args>", it does not use "exec", which leaves an undesirable resident shell process)

: "${APACHE_CONFDIR:=/etc/apache2}"
: "${APACHE_ENVVARS:=$APACHE_CONFDIR/envvars}"
if test -f "$APACHE_ENVVARS"; then
        . "$APACHE_ENVVARS"
fi

# Apache gets grumpy about PID files pre-existing
: "${APACHE_PID_FILE:=${APACHE_RUN_DIR:=/var/run/apache2}/apache2.pid}"
rm -f "$APACHE_PID_FILE"

#Added by Vince for Tito-FE to dynamically set the mysql IP at deployement time when it is needed.
#Check is done to see if it's running in a kubernetes environemen
if [ -n "$TITOSQL" ]; then
        rm /etc/apache2/mods-enabled/env.conf
        #check if K8 env
        if [ -n "$TITO_SQL_SERVICE_SERVICE_HOST" ]; then
            cat <<EOF >> /etc/apache2/mods-enabled/env.conf
                    <IfModule env_module>
                            SetEnv TITO-SQL $TITO_SQL_SERVICE_SERVICE_HOST
                    </IfModule>
            EOF        
        else
        #not K8 env
            cat <<EOF >> /etc/apache2/mods-enabled/env.conf
                    <IfModule env_module>
                            SetEnv TITO-SQL $TITOSQL
                    </IfModule>
            EOF
        fi
fi        
        




exec apache2 -DFOREGROUND "$@"
